name: ci

on: [push]

jobs:
  tests:
    name: Forge Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: dependencies
        run: |
          git clone https://github.com/0xevm/foundry.git
          cd foundry
          git checkout beijing-eth
          cargo build --release -p foundry-cli --bin forge
      - name: tests
        run:  ./foundry/target/release/forge test -vvvvv
